# Generated by Django 5.2.17 on 2026-08-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='رمز اولیه روی کاغذ تحویل می\u200cشود، پس در اولین ورود باید عوض شود', verbose_name='باید رمز را تغییر دهد'),
        ),
    ]
