# Generated by Django 5.2.17 on 2026-08-11 20:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال مالی (جلالی)')),
                ('start_date', models.DateField(verbose_name='شروع سال')),
                ('end_date', models.DateField(verbose_name='پایان سال')),
                ('is_closed', models.BooleanField(default=False, verbose_name='بسته\u200cشده')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_years', to='org.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'سال مالی',
                'verbose_name_plural': 'سال\u200cهای مالی',
                'ordering': ['-year'],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LegalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='شروع اعتبار')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('min_daily_wage', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='حداقل دستمزد روزانه')),
                ('housing_allowance', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='حق مسکن ماهانه')),
                ('food_allowance', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='بن کارگری ماهانه')),
                ('child_allowance', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='حق اولاد (هر فرزند)')),
                ('max_children', models.PositiveSmallIntegerField(default=0, help_text='صفر یعنی بدون سقف', verbose_name='حداکثر فرزند مشمول')),
                ('seniority_daily', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='پایه سنوات روزانه')),
                ('ins_employee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.07'), max_digits=7, verbose_name='سهم کارگر')),
                ('ins_employer_rate', models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=7, verbose_name='سهم کارفرما')),
                ('unemployment_rate', models.DecimalField(decimal_places=4, default=Decimal('0.03'), max_digits=7, verbose_name='بیمه بیکاری')),
                ('ins_ceiling_factor', models.DecimalField(decimal_places=4, default=Decimal('7'), help_text='سقف مبنای بیمه = این ضریب × حداقل دستمزد ماهانه', max_digits=7, verbose_name='ضریب سقف بیمه')),
                ('overtime_factor', models.DecimalField(decimal_places=4, default=Decimal('1.4'), max_digits=7, verbose_name='ضریب اضافه\u200cکاری')),
                ('night_factor', models.DecimalField(decimal_places=4, default=Decimal('0.35'), max_digits=7, verbose_name='ضریب شب\u200cکاری')),
                ('friday_factor', models.DecimalField(decimal_places=4, default=Decimal('0.4'), max_digits=7, verbose_name='ضریب جمعه\u200cکاری')),
                ('holiday_factor', models.DecimalField(decimal_places=4, default=Decimal('1.4'), max_digits=7, verbose_name='ضریب تعطیل\u200cکاری')),
                ('shift_rates', models.JSONField(blank=True, default=dict, help_text='مثال: {"MORNING_EVENING": 0.10, "MORNING_NIGHT": 0.225, "ALL": 0.15}', verbose_name='نرخ نوبت\u200cکاری')),
                ('monthly_days', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5, verbose_name='روز کارکرد ماه')),
                ('daily_work_hours', models.DecimalField(decimal_places=2, default=Decimal('7.33'), max_digits=5, verbose_name='ساعات کار روزانه')),
                ('rounding_unit', models.PositiveIntegerField(default=1000, help_text='خالص پرداختی به این واحد گرد می\u200cشود', verbose_name='واحد گرد کردن (ریال)')),
                ('deduct_insurance_from_tax_base', models.BooleanField(default=True, help_text='این تفسیر باید با حسابدار شرکت تأیید شود — روی مبلغ مالیات اثر مستقیم دارد', verbose_name='کسر بیمه سهم کارگر از درآمد مشمول مالیات')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_parameters', to='payroll_config.fiscalyear', verbose_name='سال مالی')),
            ],
            options={
                'verbose_name': 'پارامتر قانونی',
                'verbose_name_plural': 'پارامترهای قانونی',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='کد')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('kind', models.CharField(choices=[('EARNING', 'مزایا'), ('DEDUCTION', 'کسور'), ('EMPLOYER_COST', 'هزینه کارفرما'), ('INFO', 'اطلاعی')], default='EARNING', max_length=16, verbose_name='نوع')),
                ('calc_type', models.CharField(choices=[('ENGINE_RULE', 'قاعده موتور'), ('FIXED', 'مبلغ ثابت'), ('PERCENTAGE', 'درصدی از قلم دیگر'), ('MANUAL', 'ورود دستی در هر دوره')], default='ENGINE_RULE', max_length=12, verbose_name='نحوه محاسبه')),
                ('engine_rule_key', models.CharField(blank=True, help_text='نام قاعده ثبت\u200cشده در موتور محاسبه (apps/payroll/engine/rules.py)', max_length=40, verbose_name='کلید قاعده')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9, verbose_name='نرخ / ضریب')),
                ('fixed_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='مبلغ ثابت')),
                ('is_insurable', models.BooleanField(default=True, verbose_name='مشمول بیمه')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='مشمول مالیات')),
                ('affects_eid', models.BooleanField(default=True, verbose_name='در محاسبه عیدی لحاظ شود')),
                ('affects_severance', models.BooleanField(default=True, verbose_name='در محاسبه سنوات لحاظ شود')),
                ('sequence', models.PositiveSmallIntegerField(default=100, verbose_name='ترتیب محاسبه')),
                ('gl_account', models.CharField(blank=True, max_length=30, verbose_name='کد حساب دفتر کل')),
                ('color', models.CharField(default='#3E8E5B', max_length=9, verbose_name='رنگ نمایش')),
                ('print_on_payslip', models.BooleanField(default=True, verbose_name='چاپ در فیش')),
                ('is_system', models.BooleanField(default=False, help_text='اقلام سیستمی قابل حذف نیستند', verbose_name='سیستمی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='توضیح')),
                ('base_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_components', to='payroll_config.salarycomponent', verbose_name='قلم مبنا')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_components', to='org.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'قلم حقوقی',
                'verbose_name_plural': 'اقلام حقوقی',
                'ordering': ['sequence', 'id'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ComponentScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('ALL', 'همه پرسنل'), ('DEPARTMENT', 'واحد سازمانی'), ('COST_CENTER', 'مرکز هزینه'), ('JOB_TITLE', 'پست سازمانی'), ('CONTRACT_TYPE', 'نوع قرارداد'), ('EMPLOYEE', 'پرسنل مشخص')], max_length=16, verbose_name='نوع دامنه')),
                ('scope_id', models.CharField(blank=True, help_text='شناسه واحد/مرکز هزینه/پست، یا مقدار نوع قرارداد', max_length=40, verbose_name='شناسه مقصد')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='payroll_config.salarycomponent', verbose_name='قلم حقوقی')),
            ],
            options={
                'verbose_name': 'دامنه شمول',
                'verbose_name_plural': 'دامنه\u200cهای شمول',
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_order', models.PositiveSmallIntegerField(verbose_name='ترتیب پله')),
                ('basis', models.CharField(choices=[('MONTHLY', 'ماهانه'), ('ANNUAL', 'سالانه')], default='MONTHLY', max_length=8, verbose_name='مبنا')),
                ('from_amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='از مبلغ')),
                ('to_amount', models.DecimalField(blank=True, decimal_places=0, help_text='خالی یعنی بی\u200cنهایت', max_digits=18, null=True, verbose_name='تا مبلغ')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='نرخ')),
                ('is_exemption', models.BooleanField(default=False, verbose_name='ردیف معافیت')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_brackets', to='payroll_config.fiscalyear', verbose_name='سال مالی')),
            ],
            options={
                'verbose_name': 'پله مالیاتی',
                'verbose_name_plural': 'پلکان مالیات',
                'ordering': ['fiscal_year', 'row_order'],
                'unique_together': {('fiscal_year', 'row_order')},
            },
        ),
    ]
