# Generated by Django 5.2.17 on 2026-08-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalparameter',
            name='leave_day_minutes',
            field=models.PositiveSmallIntegerField(default=440, help_text='۴۴۰ دقیقه = ۷ ساعت و ۲۰ دقیقه — مطابق فیش فعلی شرکت', verbose_name='طول یک روز مرخصی (دقیقه)'),
        ),
    ]
