# Generated by Django 5.2.17 on 2026-08-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0002_legalparameter_leave_day_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalparameter',
            name='rounding_unit',
            field=models.PositiveIntegerField(default=1, help_text='۱ یعنی بدون گرد کردن (توصیه\u200cشده). مقدار بزرگ\u200cتر یک سطر «تعدیل گرد کردن» به فیش اضافه می\u200cکند که توضیحش برای پرسنل دشوار است.', verbose_name='واحد گرد کردن (ریال)'),
        ),
    ]
