# Generated by Django 5.2.17 on 2026-08-17 17:56

from django.db import migrations, models


# کد قلم -> (کلید قاعده، واحد نمایش)
DAY_COMPONENTS = {
    "ABSENCE_DED": "absence_days",
    "SICK": "sick_days",
    "UNPAID_LEAVE": "unpaid_leave_days",
}


def switch_day_components(apps, schema_editor):
    """غیبت، بیماری و مرخصی بدون حقوق: از «ورود دستی ریالی» به «سطر روزی».

    تا امروز این سه قلم مبلغ ریالی دستی می‌گرفتند. از این پس اثرشان با کم شدن
    از روز کارکرد اعمال می‌شود، پس مبلغ ریالی هم گذاشتن یعنی کسر مضاعف. سطر
    روی فیش می‌ماند ولی فقط تعداد روز نشان می‌دهد.
    """
    SalaryComponent = apps.get_model("payroll_config", "SalaryComponent")
    for code, rule_key in DAY_COMPONENTS.items():
        SalaryComponent.objects.filter(code=code).update(
            calc_type="ENGINE_RULE", engine_rule_key=rule_key, display_unit="DAY"
        )


def undo_day_components(apps, schema_editor):
    SalaryComponent = apps.get_model("payroll_config", "SalaryComponent")
    SalaryComponent.objects.filter(code__in=DAY_COMPONENTS).update(
        calc_type="MANUAL", engine_rule_key="", display_unit="RIAL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_config", "0003_alter_legalparameter_rounding_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarycomponent",
            name="display_unit",
            field=models.CharField(
                choices=[("RIAL", "ریال"), ("DAY", "روز"), ("HOUR", "ساعت")],
                default="RIAL",
                help_text="«روز» یعنی در فیش فقط تعداد روز چاپ می\u200cشود و مبلغ ریالی ندارد",
                max_length=6,
                verbose_name="واحد نمایش در فیش",
            ),
        ),
        migrations.RunPython(switch_day_components, undo_day_components),
    ]
