# Generated by Django 5.2.17 on 2026-08-18 02:32

from django.db import migrations, models


def flag_commission_and_mission(apps, schema_editor):
    """پورسانت‌ها را علامت بزن و حق مأموریت را به قاعدهٔ خودش وصل کن.

    پورسانت با کدهایی که با COMM شروع می‌شوند شناخته می‌شود — هم `COMM_1` در
    راه‌اندازی عملیاتی و هم `COMMISSION_1` در دادهٔ نمونه.

    حق مأموریت تا امروز «ورود دستی» بود؛ از این پس قاعدهٔ `mission_allowance`
    دارد که هم روزهای مأموریت جدول کارکرد را حساب می‌کند و هم مبلغ منتقل‌شده از
    پورسانت را. مبلغ دستیِ ثبت‌شده روی همین قلم هم همچنان اضافه می‌شود، پس
    دادهٔ قبلی از بین نمی‌رود.
    """
    SalaryComponent = apps.get_model("payroll_config", "SalaryComponent")
    SalaryComponent.objects.filter(code__startswith="COMM").update(is_commission=True)
    SalaryComponent.objects.filter(code="MISSION").update(
        calc_type="ENGINE_RULE", engine_rule_key="mission_allowance"
    )


def undo_flags(apps, schema_editor):
    SalaryComponent = apps.get_model("payroll_config", "SalaryComponent")
    SalaryComponent.objects.filter(code__startswith="COMM").update(is_commission=False)
    SalaryComponent.objects.filter(code="MISSION").update(
        calc_type="MANUAL", engine_rule_key=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_config", "0004_phase2_workdays_and_wage"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarycomponent",
            name="is_commission",
            field=models.BooleanField(
                default=False,
                help_text="مبلغ این اقلام وارد استخر تخصیص می\u200cشود و می\u200cتواند به حق مأموریت یا اضافه\u200cکاری منتقل شود",
                verbose_name="قلم پورسانت",
            ),
        ),
        migrations.RunPython(flag_commission_and_mission, undo_flags),
    ]
