# Generated by Django 5.2.17 on 2026-08-19 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_timesheet_items"),
        ("payroll_config", "0006_phase7_parametric_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarycomponent",
            name="timesheet_item",
            field=models.ForeignKey(
                blank=True,
                help_text="وقتی مقدار از جدول کارکرد می\u200cآید — مثل ساعت جمعه\u200cکاری",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="components",
                to="attendance.timesheetitem",
                verbose_name="قلم کارکرد",
            ),
        ),
        migrations.AlterField(
            model_name="salarycomponent",
            name="quantity_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PAID_DAYS", "روز کارکرد قابل پرداخت"),
                    ("DAY_RATIO", "به نسبت کارکرد ماه"),
                    ("TIMESHEET_ITEM", "یک قلم از جدول کارکرد"),
                    ("ONE", "ثابت (بدون ضرب در کارکرد)"),
                ],
                help_text="فقط برای قاعده پارامتری",
                max_length=16,
                verbose_name="مقدار",
            ),
        ),
    ]
