# Generated by Django 5.2.17 on 2026-08-21 11:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_config", "0007_timesheet_item_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalparameter",
            name="marriage_allowance",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="فقط به پرسنل متأهل تعلق می\u200cگیرد؛ صفر یعنی این قلم را ندارید",
                max_digits=18,
                verbose_name="حق تأهل ماهانه",
            ),
        ),
    ]
