# Generated by Django 5.2.17 on 2026-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_config", "0008_legalparameter_marriage_allowance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalparameter",
            name="child_allowance",
            field=models.DecimalField(
                decimal_places=0,
                help_text="طبق قانون = ۳ × حداقل دستمزد روزانه — مبنایش حداقل دستمزد است، نه مزد خودِ پرسنل، پس برای همه یک عدد است",
                max_digits=18,
                verbose_name="حق اولاد (هر فرزند)",
            ),
        ),
    ]
