# Generated by Django 5.2.17 on 2026-08-21 18:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_config", "0009_alter_legalparameter_child_allowance"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalparameter",
            name="mission_base",
            field=models.CharField(
                choices=[
                    (
                        "MONTHLY_RATE",
                        "مبنای روزانهٔ ثبت\u200cشده در آیتم\u200cهای ماهانه",
                    ),
                    ("PERSON_WAGE", "مزد روزانه + پایه سنوات روزانهٔ خود پرسنل"),
                ],
                default="MONTHLY_RATE",
                help_text="حالت دوم برای هر نفر عدد خودش را می\u200cگیرد، نه یک عدد مشترک",
                max_length=16,
                verbose_name="مبنای حق مأموریت",
            ),
        ),
        migrations.AddField(
            model_name="legalparameter",
            name="monthly_work_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("220"),
                help_text="مبنای اضافه\u200cکاری وقتی «مبنای ساعتی» روی حالت ماهانه باشد",
                max_digits=6,
                verbose_name="ساعات کار ماهانه",
            ),
        ),
        migrations.AddField(
            model_name="legalparameter",
            name="overtime_base",
            field=models.CharField(
                choices=[
                    (
                        "HOURLY_WAGE",
                        "مزد ساعتی خود پرسنل (مزد روزانه ÷ ساعات کار روزانه)",
                    ),
                    ("MONTHLY_BASE", "حقوق و سنوات ماهانه ÷ ساعات کار ماهانه"),
                ],
                default="HOURLY_WAGE",
                help_text="حالت دوم: (مزد روزانه × ۳۰ + پایه سنوات روزانه × کارکرد) ÷ ۲۲۰",
                max_length=16,
                verbose_name="مبنای اضافه\u200cکاری",
            ),
        ),
    ]
