# Generated by Django 5.2.17 on 2026-08-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_config", "0010_legalparameter_mission_base_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarycomponent",
            name="absorbs",
            field=models.ManyToManyField(
                blank=True,
                help_text="مبلغ این اقلام از این قلم کسر می\u200cشود، نه از خالص پرداختی",
                related_name="absorbed_by",
                to="payroll_config.salarycomponent",
                verbose_name="اقلامی که در این قلم جذب می\u200cشوند",
            ),
        ),
    ]
