# Generated by Django 5.2.17 on 2026-08-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_config", "0011_salarycomponent_absorbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarycomponent",
            name="allocation_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADD", "به استخر مازاد اضافه می\u200cشود"),
                    ("SUBTRACT", "از استخر مازاد کم می\u200cشود"),
                ],
                help_text="فقط وقتی قلم اضافه\u200cکاری یا مأموریتِ همین پرسنل از زنجیرهٔ مازاد می\u200cآید؛ وگرنه بی\u200cاثر است",
                max_length=10,
                verbose_name="نقش در استخر مازاد",
            ),
        ),
    ]
