# Generated by Django 5.2.17 on 2026-08-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0012_salarycomponent_allocation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalparameter',
            name='overtime_base',
            field=models.CharField(choices=[('HOURLY_WAGE', 'مزد ساعتی خود پرسنل (مزد روزانه ÷ ساعات کار روزانه)'), ('MONTHLY_BASE', 'حقوق و سنوات ماهانه ÷ ساعات کار ماهانه'), ('MONTHLY_BASE_30', '(مزد روزانه + پایه سنوات روزانه) × ۳۰ ÷ ساعات کار ماهانه')], default='HOURLY_WAGE', help_text='حالت دوم: (مزد روزانه × ۳۰ + پایه سنوات روزانه × کارکرد) ÷ ۲۲۰ — حالت سوم پایهٔ سنوات را هم در ۳۰ ضرب می\u200cکند، نه در کارکرد', max_length=16, verbose_name='مبنای اضافه\u200cکاری'),
        ),
    ]
