# Generated by Django 5.2.17 on 2026-08-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0013_alter_legalparameter_overtime_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalparameter',
            name='allowance_proration',
            field=models.CharField(choices=[('MONTH_DAYS', 'به نسبت روزهای همان ماه (کارکرد ÷ طول ماه)'), ('FIXED_31', 'مخرج ثابت ۳۱ — و کارکرد ۳۰ روز، کاملِ ماه')], default='MONTH_DAYS', help_text='حالت دوم روش فایل ۱۴۰۵ این شرکت است', max_length=16, verbose_name='تسهیم مزایای ثابت'),
        ),
    ]
