# Generated by Django 5.2.17 on 2026-08-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0014_legalparameter_allowance_proration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalparameter',
            name='allowance_proration',
            field=models.CharField(choices=[('MONTH_DAYS', 'به نسبت روزهای همان ماه (کارکرد ÷ طول ماه)'), ('FIXED_31', 'مخرج ثابت ۳۱ — و کارکرد ۳۰ روز، کاملِ ماه'), ('MONTH_30', 'ماهِ کامل → کامل؛ ناقص → کارکرد ÷ ۳۰')], default='MONTH_DAYS', help_text='حالت سوم رویهٔ رایج قانون کار است؛ حالت دوم روش فایل ۱۴۰۵ این شرکت', max_length=16, verbose_name='تسهیم مزایای ثابت'),
        ),
    ]
