# Generated by Django 5.2.17 on 2026-08-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0015_alter_legalparameter_allowance_proration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalparameter',
            name='allowance_proration',
            field=models.CharField(choices=[('MONTH_DAYS', 'کارکرد قابل پرداخت ÷ روزهای ماه کاری (توصیه\u200cشده)'), ('FIXED_31', 'مخرج ثابت ۳۱ — عیناً فرمول فایل ۱۴۰۵'), ('MONTH_30', 'ماهِ کامل → کامل؛ ناقص → کارکرد ÷ ۳۰')], default='MONTH_DAYS', help_text='حالت اول: ماهِ کامل همیشه کامل پرداخت می\u200cشود — چه ۲۹ روزه چه ۳۱ روزه — و فقط غیبت و بیماری و مرخصی بدون حقوق کمش می\u200cکنند. «روزهای ماه کاری» هر دوره در ساخت همان دوره تعیین می\u200cشود.', max_length=16, verbose_name='تسهیم مزایای ثابت'),
        ),
    ]
