# Generated by Django 5.2.17 on 2026-08-26 22:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0016_alter_legalparameter_allowance_proration'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalparameter',
            name='annual_leave_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('26'), help_text='سهمیهٔ کسی که تمام سال را کار کرده. سهمیهٔ استخدام\u200cشدهٔ وسط سال از همین عدد و به تناسب ۳۶۵ روز حساب می\u200cشود.', max_digits=5, verbose_name='مرخصی استحقاقی سال کامل (روز)'),
        ),
    ]
