# Generated by Django 5.2.17 on 2026-09-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0017_legalparameter_annual_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponent',
            name='adds',
            field=models.ManyToManyField(blank=True, help_text='مبلغ این اقلام پیش از کسر جذب\u200cشونده\u200cها به این قلم اضافه می\u200cشود', related_name='added_to', to='payroll_config.salarycomponent', verbose_name='اقلامی که به این قلم اضافه می\u200cشوند'),
        ),
    ]
