# Generated by Django 5.2.17 on 2026-09-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0018_salarycomponent_adds'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponent',
            name='show_quantity',
            field=models.BooleanField(default=True, help_text='برای اقلامی که تعدادشان روزهای ماه است، خاموش کنید', verbose_name='نمایش تعداد روی فیش'),
        ),
    ]
