# Generated by Django 5.2.17 on 2026-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0019_salarycomponent_show_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalparameter',
            name='seniority_monthly_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='فقط در ماخذ کسر کار و تأخیر استفاده می\u200cشود؛ تبریز ۳۰، اردبیل ۳۱', verbose_name='ضریب پایه سنوات ماهانه (روز)'),
        ),
    ]
