# Generated by Django 5.2.17 on 2026-09-07 18:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_config', '0020_legalparameter_seniority_monthly_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalparameter',
            name='monthly_work_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('11440'), help_text='مخرجِ بخشِ دقیقهٔ کسر تأخیر. در فایل شرکت ۱۱۴۴۰ است (۲۶ روز × ۴۴۰ دقیقه)، نه ۱۳۲۰۰', max_digits=8, verbose_name='دقایق کار ماهانه'),
        ),
        migrations.AlterField(
            model_name='legalparameter',
            name='monthly_work_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('220'), help_text='مبنای اضافه\u200cکاری وقتی «مبنای ساعتی» روی حالت ماهانه باشد، و مخرجِ بخشِ ساعتِ کسر تأخیر', max_digits=6, verbose_name='ساعات کار ماهانه'),
        ),
    ]
