# Generated by Django 5.2.17 on 2026-08-11 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='نام حقوقی')),
                ('national_id', models.CharField(blank=True, max_length=11, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='شماره ثبت')),
                ('insurance_workshop_code', models.CharField(blank=True, max_length=20, verbose_name='کد کارگاه تأمین اجتماعی')),
                ('tax_file_number', models.CharField(blank=True, max_length=20, verbose_name='شماره پرونده مالیاتی')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شعبه')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='کد')),
                ('insurance_branch_code', models.CharField(blank=True, max_length=20, verbose_name='کد شعبه بیمه')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='org.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعب',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرکز هزینه')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='کد')),
                ('gl_account', models.CharField(blank=True, max_length=30, verbose_name='کد حساب دفتر کل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='org.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'مرکز هزینه',
                'verbose_name_plural': 'مراکز هزینه',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام واحد')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='کد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='org.company', verbose_name='شرکت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='org.department', verbose_name='واحد بالادست')),
            ],
            options={
                'verbose_name': 'واحد سازمانی',
                'verbose_name_plural': 'واحدهای سازمانی',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان شغلی')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='کد')),
                ('job_group', models.PositiveSmallIntegerField(blank=True, help_text='بر اساس طرح طبقه\u200cبندی مشاغل', null=True, verbose_name='گروه شغلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_titles', to='org.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'پست سازمانی',
                'verbose_name_plural': 'پست\u200cهای سازمانی',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
