# Generated by Django 5.2.17 on 2026-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_file_columns',
            field=models.CharField(default='row,account,amount', help_text='با کاما جدا کنید. مقادیر مجاز: row, personnel_code, national_id, name, account, iban, amount, description', max_length=200, verbose_name='ستون\u200cهای فایل بانک'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_file_delimiter',
            field=models.CharField(default=',', help_text='مثلاً , یا ; یا | — برای tab بنویسید \\t', max_length=5, verbose_name='جداکننده'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_file_encoding',
            field=models.CharField(default='utf-8-sig', help_text='utf-8-sig برای اکسل فارسی · cp1256 برای سامانه\u200cهای قدیمی', max_length=20, verbose_name='کدگذاری فایل'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_file_extension',
            field=models.CharField(default='txt', max_length=8, verbose_name='پسوند فایل'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_file_include_header',
            field=models.BooleanField(default=False, verbose_name='سطر عنوان داشته باشد'),
        ),
    ]
