# Generated by Django 5.2.17 on 2026-08-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_phase6_org_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activity',
            field=models.CharField(blank=True, help_text='زیر نام شرکت روی سربرگ فیش چاپ می\u200cشود', max_length=120, verbose_name='زمینه فعالیت'),
        ),
    ]
