# Generated by Django 5.2.17 on 2026-08-11 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('LOAN', 'وام'), ('ADVANCE', 'مساعده')], default='LOAN', max_length=8, verbose_name='نوع')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('principal', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ اصل (ریال)')),
                ('total_installments', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد اقساط')),
                ('installment_amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ هر قسط')),
                ('grant_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('first_year', models.PositiveSmallIntegerField(verbose_name='سال اولین قسط')),
                ('first_month', models.PositiveSmallIntegerField(verbose_name='ماه اولین قسط')),
                ('status', models.CharField(choices=[('ACTIVE', 'جاری'), ('SETTLED', 'تسویه\u200cشده'), ('SUSPENDED', 'معلق'), ('CANCELLED', 'لغوشده')], default='ACTIVE', max_length=10, verbose_name='وضعیت')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'وام و مساعده',
                'verbose_name_plural': 'وام و مساعده',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='شماره قسط')),
                ('due_year', models.PositiveSmallIntegerField(verbose_name='سال سررسید')),
                ('due_month', models.PositiveSmallIntegerField(verbose_name='ماه سررسید')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('PENDING', 'سررسید نشده'), ('DUE', 'سررسید'), ('DEDUCTED', 'کسر شده'), ('SKIPPED', 'رد شده'), ('WAIVED', 'بخشیده شده')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('deducted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان کسر')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan', verbose_name='وام')),
                ('payslip_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_installments', to='payroll.payslipline', verbose_name='سطر کسر')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'ordering': ['loan', 'number'],
                'indexes': [models.Index(fields=['due_year', 'due_month', 'status'], name='loans_loani_due_yea_8a1339_idx')],
                'unique_together': {('loan', 'number')},
            },
        ),
    ]
