# Generated by Django 5.2.17 on 2026-08-11 20:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='نام فایل')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='تعداد سطر')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='تعداد خطا')),
                ('log', models.JSONField(blank=True, default=list, verbose_name='گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_imports', to=settings.AUTH_USER_MODEL, verbose_name='واردکننده')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_imports', to='payroll.payrollperiod', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'ورود کارکرد از فایل',
                'verbose_name_plural': 'ورود کارکرد از فایل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=6, verbose_name='روز کارکرد')),
                ('absence_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='غیبت')),
                ('unpaid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مرخصی بدون حقوق')),
                ('paid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مرخصی استحقاقی')),
                ('sick_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مرخصی استعلاجی')),
                ('mission_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مأموریت')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='اضافه\u200cکاری (ساعت)')),
                ('night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='شب\u200cکاری (ساعت)')),
                ('friday_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='جمعه\u200cکاری (ساعت)')),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='تعطیل\u200cکاری (ساعت)')),
                ('shift_type', models.CharField(choices=[('NONE', 'بدون نوبت\u200cکاری'), ('MORNING_EVENING', 'صبح و عصر'), ('MORNING_NIGHT', 'صبح و شب'), ('ALL', 'صبح، عصر و شب')], default='NONE', max_length=20, verbose_name='نوبت\u200cکاری')),
                ('source', models.CharField(choices=[('MANUAL', 'ورود دستی'), ('IMPORT', 'فایل اکسل'), ('DEVICE', 'دستگاه حضور و غیاب')], default='MANUAL', max_length=8, verbose_name='منبع')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('SUBMITTED', 'ارسال\u200cشده'), ('APPROVED', 'تأییدشده')], default='DRAFT', max_length=10, verbose_name='وضعیت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='employees.employmentcontract', verbose_name='قرارداد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='employees.employee', verbose_name='پرسنل')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='payroll.payrollperiod', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'کارکرد ماهانه',
                'verbose_name_plural': 'کارکرد ماهانه',
                'ordering': ['employee__personnel_code'],
                'indexes': [models.Index(fields=['period', 'status'], name='attendance__period__3377f1_idx')],
                'unique_together': {('period', 'employee')},
            },
        ),
    ]
