# Generated by Django 5.2.17 on 2026-08-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        ('payroll_config', '0002_legalparameter_leave_day_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='leave_minutes',
            field=models.IntegerField(default=0, verbose_name='مرخصی استحقاقی (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='خودکار از روی دقیقه محاسبه می\u200cشود', max_digits=6, verbose_name='مرخصی استحقاقی (روز)'),
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carried_over_minutes', models.IntegerField(default=0, verbose_name='انتقالی از سال قبل (دقیقه)')),
                ('annual_minutes', models.IntegerField(default=0, verbose_name='استحقاقی سال (دقیقه)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to='employees.employee', verbose_name='پرسنل')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_entitlements', to='payroll_config.fiscalyear', verbose_name='سال مالی')),
            ],
            options={
                'verbose_name': 'سهمیه مرخصی',
                'verbose_name_plural': 'سهمیه\u200cهای مرخصی',
                'unique_together': {('employee', 'fiscal_year')},
            },
        ),
    ]
