# Generated by Django 5.2.17 on 2026-08-16 05:27

from django.db import migrations, models
from django.db.models import F


def fill_overtime_minutes(apps, schema_editor):
    """اضافه‌کاریِ ثبت‌شده را از ساعت به دقیقه منتقل می‌کند.

    بدون این قدم، اولین ذخیرهٔ هر کارکردِ قدیمی اضافه‌کاری‌اش را صفر می‌کرد،
    چون از این به بعد ساعت از روی دقیقه ساخته می‌شود نه برعکس.
    """
    Timesheet = apps.get_model("attendance", "Timesheet")
    Timesheet.objects.update(overtime_minutes=F("overtime_hours") * 60)


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_timesheet_leave_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="overtime_minutes",
            field=models.IntegerField(
                default=0, verbose_name="اضافه\u200cکاری (دقیقه)"
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="خودکار از روی دقیقه محاسبه می\u200cشود",
                max_digits=6,
                verbose_name="اضافه\u200cکاری (ساعت)",
            ),
        ),
        migrations.RunPython(fill_overtime_minutes, migrations.RunPython.noop),
    ]
