# Generated by Django 5.2.17 on 2026-08-18 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_timesheet_overtime_minutes"),
        ("employees", "0005_phase2_workdays_and_wage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ENTITLED", "استحقاقی"),
                            ("UNPAID", "بدون حقوق"),
                            ("SICK", "استعلاجی"),
                        ],
                        default="ENTITLED",
                        max_length=10,
                        verbose_name="نوع مرخصی",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="از تاریخ")),
                ("end_date", models.DateField(verbose_name="تا تاریخ")),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="مبنای ذخیره دقیقه است؛ روز و ساعت از روی همین ساخته می\u200cشوند",
                        verbose_name="مدت (دقیقه)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "ثبت\u200cشده"),
                            ("CANCELLED", "لغوشده"),
                        ],
                        default="REGISTERED",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="علت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_records",
                        to="employees.employee",
                        verbose_name="پرسنل",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرخصی",
                "verbose_name_plural": "کارتابل مرخصی",
                "ordering": ["-start_date", "employee__personnel_code"],
                "indexes": [
                    models.Index(
                        fields=["employee", "start_date", "end_date"],
                        name="attendance__employe_27400c_idx",
                    )
                ],
            },
        ),
    ]
