# Generated by Django 5.2.17 on 2026-08-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_timesheet_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="خودکار از روی دقیقه محاسبه می\u200cشود — فقط برای نمایش",
                max_digits=6,
                verbose_name="اضافه\u200cکاری (ساعت)",
            ),
        ),
    ]
