# Generated by Django 5.2.17 on 2026-08-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_timesheet_overtime_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveentitlement',
            name='opening_through_month',
            field=models.PositiveSmallIntegerField(default=0, help_text='۰ یعنی افتتاحیه\u200cای در کار نیست و همه\u200cچیز از کارکرد ساخته می\u200cشود', verbose_name='این عدد تا پایان کدام ماه است'),
        ),
        migrations.AddField(
            model_name='leaveentitlement',
            name='opening_used_minutes',
            field=models.IntegerField(default=0, help_text='مرخصی استفاده\u200cشده از اول سال تا ماهی که سامانه عملیاتی شد', verbose_name='مصرفی پیش از راه\u200cاندازی سامانه (دقیقه)'),
        ),
    ]
