# Generated by Django 5.2.17 on 2026-08-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_leaveentitlement_opening_through_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='overtime_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='خالی بگذارید تا از ساعت و مبنای سال مالی حساب شود', max_digits=18, null=True, verbose_name='مبلغ اضافه\u200cکاری (ریال)'),
        ),
    ]
