# Generated by Django 5.2.17 on 2026-08-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_timesheet_overtime_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='late_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='تأخیر ورود (ساعت)'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='late_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تأخیر ورود (دقیقه)'),
        ),
    ]
