# Generated by Django 5.2.17 on 2026-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_timesheet_late_hours_timesheet_late_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveentitlement',
            name='annual_is_manual',
            field=models.BooleanField(default=False, help_text='اگر خاموش باشد، سهمیه از تاریخ استخدام محاسبه می\u200cشود', verbose_name='استحقاقی سال دستی وارد شده'),
        ),
    ]
