# Generated by Django 5.2.17 on 2026-08-11 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('org', '0001_initial'),
        ('payroll_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال (جلالی)')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ماه')),
                ('start_date', models.DateField(verbose_name='شروع دوره')),
                ('end_date', models.DateField(verbose_name='پایان دوره')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('TIMESHEET_LOCKED', 'کارکرد قفل\u200cشده'), ('CALCULATED', 'محاسبه\u200cشده'), ('APPROVED', 'تأییدشده'), ('LOCKED', 'قفل\u200cشده'), ('PAID', 'پرداخت\u200cشده')], default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('total_gross', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='ناخالص کل')),
                ('total_net', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='خالص کل')),
                ('total_deductions', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='جمع کسور')),
                ('total_employer_cost', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='هزینه کارفرما')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پرسنل')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان محاسبه')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان قفل')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='org.company', verbose_name='شرکت')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='payroll_config.fiscalyear', verbose_name='سال مالی')),
                ('legal_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='payroll_config.legalparameter', verbose_name='پارامتر اعمال\u200cشده')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL, verbose_name='قفل\u200cکننده')),
            ],
            options={
                'verbose_name': 'دوره حقوقی',
                'verbose_name_plural': 'دوره\u200cهای حقوقی',
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('status', models.CharField(choices=[('RUNNING', 'در حال اجرا'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق')], default='RUNNING', max_length=10, verbose_name='وضعیت')),
                ('engine_version', models.CharField(blank=True, max_length=20, verbose_name='نسخه موتور')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='موفق')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='خطا')),
                ('error_detail', models.JSONField(blank=True, default=list, verbose_name='جزئیات خطا')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='payroll.payrollperiod', verbose_name='دوره')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='اجراکننده')),
            ],
            options={
                'verbose_name': 'اجرای محاسبه',
                'verbose_name_plural': 'اجراهای محاسبه',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban_snapshot', models.CharField(blank=True, max_length=26, verbose_name='شبا در لحظه پرداخت')),
                ('params_snapshot', models.JSONField(blank=True, default=dict, verbose_name='تصویر پارامترهای قانونی')),
                ('work_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='روز کارکرد')),
                ('gross_total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='ناخالص کل')),
                ('insurable_base', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبنای بیمه')),
                ('taxable_base', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبنای مالیات')),
                ('total_deductions', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع کسور')),
                ('net_payable', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='خالص پرداختی')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مالیات')),
                ('ins_employee', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بیمه سهم کارگر')),
                ('ins_employer', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بیمه سهم کارفرما')),
                ('employer_total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='کل هزینه کارفرما')),
                ('status', models.CharField(choices=[('CALCULATED', 'محاسبه\u200cشده'), ('APPROVED', 'تأییدشده'), ('PAID', 'پرداخت\u200cشده'), ('CANCELLED', 'ابطال\u200cشده')], default='CALCULATED', max_length=12, verbose_name='وضعیت')),
                ('is_corrective', models.BooleanField(default=False, verbose_name='فیش اصلاحی')),
                ('calc_hash', models.CharField(blank=True, max_length=64, verbose_name='اثر انگشت محاسبه')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان محاسبه')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('payment_reference', models.CharField(blank=True, max_length=60, verbose_name='مرجع پرداخت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employmentcontract', verbose_name='قرارداد')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='org.costcenter', verbose_name='مرکز هزینه')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='org.department', verbose_name='واحد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee', verbose_name='پرسنل')),
                ('original_payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='payroll.payslip', verbose_name='فیش اصلی')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollperiod', verbose_name='دوره')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='payroll.payrollrun', verbose_name='اجرای محاسبه')),
            ],
            options={
                'verbose_name': 'فیش حقوقی',
                'verbose_name_plural': 'فیش\u200cهای حقوقی',
                'ordering': ['employee__personnel_code'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(max_length=40, verbose_name='کد قلم')),
                ('component_name', models.CharField(max_length=80, verbose_name='نام قلم')),
                ('kind', models.CharField(choices=[('EARNING', 'مزایا'), ('DEDUCTION', 'کسور'), ('EMPLOYER_COST', 'هزینه کارفرما'), ('INFO', 'اطلاعی')], max_length=16, verbose_name='نوع')),
                ('sequence', models.PositiveSmallIntegerField(default=100, verbose_name='ترتیب')),
                ('base_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبنا')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تعداد / ساعت')),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='ضریب / نرخ')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ')),
                ('is_insurable', models.BooleanField(default=False, verbose_name='مشمول بیمه')),
                ('is_taxable', models.BooleanField(default=False, verbose_name='مشمول مالیات')),
                ('explanation', models.CharField(blank=True, help_text='مثال: اضافه\u200cکاری: ۱۲ ساعت × (۸۵٬۰۰۰٬۰۰۰ ÷ ۳۰ ÷ ۷٫۳۳) × ۱٫۴', max_length=255, verbose_name='توضیح محاسبه')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='payroll_config.salarycomponent', verbose_name='قلم حقوقی')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip', verbose_name='فیش')),
            ],
            options={
                'verbose_name': 'سطر فیش',
                'verbose_name_plural': 'سطرهای فیش',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayslipView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان مشاهده')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='payroll.payslip', verbose_name='فیش')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_views', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشاهده فیش',
                'verbose_name_plural': 'مشاهدات فیش',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ (ریال)')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='توضیح')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inputs', to='payroll_config.salarycomponent', verbose_name='قلم حقوقی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_inputs', to='employees.employee', verbose_name='پرسنل')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='payroll.payrollperiod', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'ورودی دستی دوره',
                'verbose_name_plural': 'ورودی\u200cهای دستی دوره',
                'unique_together': {('period', 'employee', 'component')},
            },
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['period', 'employee'], name='payroll_pay_period__66dc5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(condition=models.Q(('is_corrective', False)), fields=('period', 'employee'), name='unique_payslip_per_period_employee'),
        ),
        migrations.AddIndex(
            model_name='payslipline',
            index=models.Index(fields=['payslip', 'sequence'], name='payroll_pay_payslip_72407a_idx'),
        ),
    ]
