# Generated by Django 5.2.17 on 2026-08-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('org', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payslip',
            name='unique_payslip_per_period_employee',
        ),
        migrations.AddField(
            model_name='payslip',
            name='revision',
            field=models.PositiveSmallIntegerField(default=0, help_text='۰ = فیش اصلی دوره، ۱ به بعد = فیش\u200cهای اصلاحی', verbose_name='شماره اصلاح'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('period', 'employee', 'revision'), name='unique_payslip_per_period_employee'),
        ),
    ]
