# Generated by Django 5.2.17 on 2026-08-15 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_payslip_unique_payslip_per_period_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='ack_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار مشاهده'), ('VIEWED', 'دیده شد'), ('ACCEPTED', 'تأیید شد'), ('DISPUTED', 'اعتراض ثبت شد'), ('RESOLVED', 'بررسی و پاسخ داده شد')], default='PENDING', max_length=10, verbose_name='وضعیت تأیید پرسنل'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='dispute_reason',
            field=models.TextField(blank=True, verbose_name='علت اعتراض'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت اعتراض'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='first_viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='اولین مشاهده'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='پاسخ واحد مالی'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payslips', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده'),
        ),
    ]
