# Generated by Django 5.2.17 on 2026-08-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payslip_ack_status_payslip_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='leave_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='انتقالی، استحقاقی، مصرفی ماه، مصرفی از اول سال و مانده — در لحظه محاسبه', verbose_name='تصویر مانده مرخصی'),
        ),
    ]
