# Generated by Django 5.2.17 on 2026-08-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payslip_leave_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='account_snapshot',
            field=models.CharField(blank=True, max_length=30, verbose_name='شماره حساب در لحظه پرداخت'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='bank_snapshot',
            field=models.CharField(blank=True, max_length=60, verbose_name='بانک عامل'),
        ),
    ]
