# Generated by Django 5.2.17 on 2026-08-15 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payslip_account_snapshot_payslip_bank_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INSURANCE', 'لیست بیمه (DSK)'), ('TAX', 'لیست مالیات'), ('BANK', 'فایل پرداخت بانک')], max_length=12, verbose_name='نوع خروجی')),
                ('file', models.FileField(upload_to='exports/%Y/%m/', verbose_name='فایل')),
                ('file_name', models.CharField(max_length=160, verbose_name='نام فایل')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='تعداد رکورد')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='جمع مبلغ')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='خلاصه ارقام')),
                ('status', models.CharField(choices=[('GENERATED', 'تولید شده'), ('SUBMITTED', 'ارسال شده'), ('ACCEPTED', 'پذیرفته شده'), ('REJECTED', 'رد شده')], default='GENERATED', max_length=10, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(blank=True, max_length=60, verbose_name='کد رهگیری')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='توضیح')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_exports', to=settings.AUTH_USER_MODEL, verbose_name='تولیدکننده')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='payroll.payrollperiod', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'خروجی قانونی',
                'verbose_name_plural': 'خروجی\u200cهای قانونی',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['period', 'kind'], name='payroll_pay_period__0eabd8_idx')],
            },
        ),
    ]
