# Generated by Django 5.2.17 on 2026-08-17 17:28

from django.db import migrations, models


def fill_insurance_applies(apps, schema_editor):
    """فیش‌های قبلی: مشمولیت بیمه را از قرارداد همان فیش بردار.

    تیک «بازنشسته» تا امروز وجود نداشته، پس تنها منبعِ درست برای گذشته همان
    `EmploymentContract.is_insured` است. بدون این قدم، قراردادهای غیرمشمول در
    گزارش بیمهٔ ماه‌های گذشته دوباره ظاهر می‌شدند.
    """
    Payslip = apps.get_model("payroll", "Payslip")
    Payslip.objects.filter(contract__is_insured=False).update(insurance_applies=False)


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_payrollexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="insurance_applies",
            field=models.BooleanField(
                default=True,
                help_text="در لحظه محاسبه ثبت می\u200cشود؛ پرسنل بازنشسته و قرارداد غیرمشمول، False",
                verbose_name="مشمول بیمه",
            ),
        ),
        migrations.RunPython(fill_insurance_applies, migrations.RunPython.noop),
    ]
