# Generated by Django 5.2.17 on 2026-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0007_retired_and_insurance_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslipline",
            name="display_unit",
            field=models.CharField(
                choices=[("RIAL", "ریال"), ("DAY", "روز"), ("HOUR", "ساعت")],
                default="RIAL",
                max_length=6,
                verbose_name="واحد نمایش",
            ),
        ),
    ]
