# Generated by Django 5.2.17 on 2026-08-18 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0008_phase2_workdays_and_wage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, verbose_name="کلید پارامتر")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="مقدار"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=160, verbose_name="توضیح"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_parameters",
                        to="payroll.payrollperiod",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_parameters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم محاسباتی ماهانه",
                "verbose_name_plural": "آیتم\u200cهای محاسباتی ماهانه",
                "ordering": ["key"],
                "unique_together": {("period", "key")},
            },
        ),
    ]
