# Generated by Django 5.2.17 on 2026-08-18 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_phase2_workdays_and_wage"),
        ("payroll", "0009_phase3_monthly_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="پورسانت اولیه",
                    ),
                ),
                (
                    "to_mission",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="منتقل\u200cشده به حق مأموریت",
                    ),
                ),
                (
                    "mission_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="روز مأموریت معادل",
                    ),
                ),
                (
                    "to_overtime",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="منتقل\u200cشده به اضافه\u200cکاری",
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="ساعت اضافه\u200cکاری معادل",
                    ),
                ),
                (
                    "remaining",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="ماندهٔ پورسانت",
                    ),
                ),
                (
                    "mission_daily_rate",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="مبنای روزانه مأموریت",
                    ),
                ),
                (
                    "mission_max_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="سقف روز مأموریت",
                    ),
                ),
                (
                    "overtime_hourly_rate",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="مبنای ساعتی اضافه\u200cکاری",
                    ),
                ),
                (
                    "overtime_max_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="سقف ساعت اضافه\u200cکاری",
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="کاربر تقسیم خودکار را تغییر داده است",
                        verbose_name="تخصیص دستی",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=160, verbose_name="توضیح"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_allocations",
                        to="employees.employee",
                        verbose_name="پرسنل",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_allocations",
                        to="payroll.payrollperiod",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_allocations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص پورسانت",
                "verbose_name_plural": "تخصیص پورسانت",
                "ordering": ["employee__personnel_code"],
                "unique_together": {("period", "employee")},
            },
        ),
    ]
