# Generated by Django 5.2.17 on 2026-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0010_phase4_commission_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="insurance_applies",
            field=models.BooleanField(
                default=True,
                help_text="در لحظه محاسبه ثبت می\u200cشود؛ پرسنلِ بدون بیمه و قرارداد غیرمشمول، False",
                verbose_name="مشمول بیمه",
            ),
        ),
    ]
