# Generated by Django 5.2.17 on 2026-08-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_payslip_insurance_applies'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='base_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='خالی یعنی از تقویم همان ماه گرفته شود', null=True, verbose_name='روزهای ماه کاری'),
        ),
    ]
