# Generated by Django 5.2.17 on 2026-08-11 20:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('payroll_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=20, verbose_name='کد پرسنلی')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(max_length=80, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=60, verbose_name='نام پدر')),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید دقیقاً ۱۰ رقم باشد.')], verbose_name='کد ملی')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='شماره شناسنامه')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], default='M', max_length=1, verbose_name='جنسیت')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'مجرد'), ('MARRIED', 'متأهل')], default='SINGLE', max_length=10, verbose_name='وضعیت تأهل')),
                ('insurance_number', models.CharField(blank=True, max_length=15, verbose_name='شماره بیمه')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('hire_date', models.DateField(verbose_name='تاریخ استخدام')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خروج')),
                ('termination_reason', models.CharField(blank=True, max_length=120, verbose_name='علت خروج')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('SUSPENDED', 'معلق'), ('TERMINATED', 'خاتمه\u200cیافته')], default='ACTIVE', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='org.company', verbose_name='شرکت')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='کاربر پرتال')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'ordering': ['personnel_code'],
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('SPOUSE', 'همسر'), ('CHILD', 'فرزند'), ('PARENT', 'والدین')], max_length=10, verbose_name='نسبت')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('child_allowance_eligible', models.BooleanField(default=False, verbose_name='مشمول حق اولاد')),
                ('is_insured', models.BooleanField(default=True, verbose_name='تحت پوشش بیمه')),
                ('start_date', models.DateField(verbose_name='شروع تکفل')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='پایان تکفل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'فرد تحت تکفل',
                'verbose_name_plural': 'افراد تحت تکفل',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=60, verbose_name='بانک')),
                ('bank_code', models.CharField(blank=True, max_length=10, verbose_name='کد بانک')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='شماره حساب')),
                ('iban', models.CharField(max_length=26, validators=[django.core.validators.RegexValidator('^IR\\d{24}$', 'شماره شبا باید با IR شروع شود و ۲۶ کاراکتر باشد.')], verbose_name='شماره شبا')),
                ('is_default', models.BooleanField(default=True, verbose_name='حساب پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='employees.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=30, verbose_name='شماره قرارداد')),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'دائم'), ('TEMPORARY', 'موقت'), ('HOURLY', 'ساعتی'), ('DAILY', 'روزمزد'), ('TRIAL', 'آزمایشی')], default='PERMANENT', max_length=12, verbose_name='نوع قرارداد')),
                ('effective_from', models.DateField(verbose_name='شروع اعتبار')),
                ('effective_to', models.DateField(blank=True, help_text='خالی یعنی قرارداد جاری', null=True, verbose_name='پایان اعتبار')),
                ('base_salary', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='حقوق پایه ماهانه (ریال)')),
                ('seniority_years', models.PositiveSmallIntegerField(default=0, verbose_name='سابقه (سال) برای پایه سنوات')),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=Decimal('44'), max_digits=5, verbose_name='ساعت کار هفتگی')),
                ('is_insured', models.BooleanField(default=True, verbose_name='مشمول بیمه')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='مشمول مالیات')),
                ('tax_exemption', models.CharField(choices=[('NONE', 'بدون معافیت خاص'), ('FREE_ZONE', 'مناطق آزاد'), ('DISABLED', 'معلولین')], default='NONE', max_length=12, verbose_name='معافیت مالیاتی')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('ACTIVE', 'فعال'), ('ENDED', 'پایان\u200cیافته')], default='ACTIVE', max_length=8, verbose_name='وضعیت')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='تاریخ امضا')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='org.costcenter', verbose_name='مرکز هزینه')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='org.department', verbose_name='واحد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.employee', verbose_name='پرسنل')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='org.jobtitle', verbose_name='پست سازمانی')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ContractAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='مبلغ (ریال)')),
                ('effective_from', models.DateField(verbose_name='شروع اعتبار')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_allowances', to='payroll_config.salarycomponent', verbose_name='قلم حقوقی')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='employees.employmentcontract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'مزایای مستمر قرارداد',
                'verbose_name_plural': 'مزایای مستمر قرارداد',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'last_name'], name='employees_e_status_96133d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'personnel_code')},
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['employee', 'effective_from', 'effective_to'], name='employees_e_employe_fc3e32_idx'),
        ),
    ]
