# Generated by Django 5.2.17 on 2026-08-15 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.ImageField(blank=True, help_text='تصویر امضا با زمینه روشن — روی فیش تأییدشده چاپ می\u200cشود', null=True, upload_to='signatures/', verbose_name='تصویر امضا'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=30, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='رسالت', max_length=60, verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, help_text='اختیاری — پرداخت بر مبنای شماره حساب انجام می\u200cشود', max_length=26, validators=[django.core.validators.RegexValidator('^IR\\d{24}$', 'شماره شبا باید با IR شروع شود و ۲۶ کاراکتر باشد.')], verbose_name='شماره شبا'),
        ),
    ]
