# Generated by Django 5.2.17 on 2026-08-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_bankaccount_card_number_employee_signature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_code",
            field=models.CharField(
                blank=True,
                help_text="خودکار از روی نام بانک پر می\u200cشود",
                max_length=10,
                verbose_name="کد بانک",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(
                choices=[
                    ("رسالت", "رسالت"),
                    ("ملی", "ملی"),
                    ("ملت", "ملت"),
                    ("صادرات", "صادرات"),
                    ("تجارت", "تجارت"),
                    ("سپه", "سپه"),
                    ("کشاورزی", "کشاورزی"),
                    ("مسکن", "مسکن"),
                    ("رفاه کارگران", "رفاه کارگران"),
                    ("صنعت و معدن", "صنعت و معدن"),
                    ("توسعه صادرات", "توسعه صادرات"),
                    ("توسعه تعاون", "توسعه تعاون"),
                    ("پست بانک", "پست بانک"),
                    ("پارسیان", "پارسیان"),
                    ("پاسارگاد", "پاسارگاد"),
                    ("سامان", "سامان"),
                    ("سینا", "سینا"),
                    ("سرمایه", "سرمایه"),
                    ("اقتصاد نوین", "اقتصاد نوین"),
                    ("کارآفرین", "کارآفرین"),
                    ("شهر", "شهر"),
                    ("دی", "دی"),
                    ("آینده", "آینده"),
                    ("گردشگری", "گردشگری"),
                    ("ایران زمین", "ایران زمین"),
                    ("مهر ایران", "مهر ایران"),
                    ("کوثر", "کوثر"),
                    ("ملل", "ملل"),
                    ("خاورمیانه", "خاورمیانه"),
                    ("نور", "نور"),
                    ("ایران ونزوئلا", "ایران ونزوئلا"),
                ],
                default="رسالت",
                max_length=60,
                verbose_name="بانک",
            ),
        ),
    ]
