# Generated by Django 5.2.17 on 2026-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_bankaccount_bank_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_retired",
            field=models.BooleanField(
                default=False,
                help_text="برای پرسنل بازنشسته حق بیمه محاسبه نمی\u200cشود و در لیست تأمین اجتماعی نمی\u200cآید",
                verbose_name="بازنشسته",
            ),
        ),
    ]
