# Generated by Django 5.2.17 on 2026-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_retired_and_insurance_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="rehire_date",
            field=models.DateField(
                blank=True,
                help_text="اگر پس از خاتمه دوباره مشغول به کار شده — از این تاریخ دوباره کارکرد دارد",
                null=True,
                verbose_name="تاریخ شروع به کار مجدد",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="termination_date",
            field=models.DateField(
                blank=True,
                help_text="از این تاریخ به بعد کارکرد ندارد؛ خودِ این روز جزو کارکرد نیست",
                null=True,
                verbose_name="تاریخ خاتمه کار",
            ),
        ),
    ]
