# Generated by Django 5.2.17 on 2026-08-26 21:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_prior_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentcontract',
            name='cumulative_seniority_daily',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='انباشتهٔ سال\u200cهای خدمت. مابه\u200cالتفاوت با پایه سنوات سال، روی فیش می\u200cآید.', max_digits=18, verbose_name='پایه سنوات تجمیعی روزانه'),
        ),
    ]
