# Generated by Django 5.2.17 on 2026-09-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employmentcontract_cumulative_seniority_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_to_mission',
            field=models.BooleanField(default=True, help_text='خاموش کنید تا پورسانت این نفر تبدیل نشود و کامل در سطر پورسانت بماند', verbose_name='تبدیل پورسانت به مأموریت و اضافه\u200cکاری'),
        ),
    ]
